// Generated by CoffeeScript 1.12.7
var DomainResource, ElementMenu, React, ResourceElement, State,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

React = require("react");

State = require("../state");

ResourceElement = require("./resource-element");

ElementMenu = require("./element-menu");

DomainResource = (function(superClass) {
  extend(DomainResource, superClass);

  function DomainResource() {
    return DomainResource.__super__.constructor.apply(this, arguments);
  }

  DomainResource.prototype.shouldComponentUpdate = function(nextProps) {
    return nextProps.node !== this.props.node;
  };

  DomainResource.prototype.render = function() {
    var child, children, i, id, len, node, ref, resourceId;
    if (!(node = this.props.node)) {
      return null;
    }
    resourceId = null;
    children = [];
    ref = node.children;
    for (i = 0, len = ref.length; i < len; i++) {
      child = ref[i];
      if (child.name === "id") {
        resourceId = child.value;
      }
      children.push(React.createElement(ResourceElement, {
        "key": child.id,
        "node": child,
        "parent": node
      }));
    }
    id = resourceId ? React.createElement("span", {
      "className": "small"
    }, "  (", resourceId, ")") : void 0;
    return React.createElement("div", {
      "className": "fhir-resource"
    }, React.createElement("div", {
      "className": " fhir-resource-title row"
    }, React.createElement("div", {
      "className": "col-sm-12"
    }, React.createElement("h2", null, node.displayName, id, "\t\t\t\t\t ", React.createElement(ElementMenu, {
      "node": node
    })))), children);
  };

  return DomainResource;

})(React.Component);

module.exports = DomainResource;
